---

services:
  gitlab:
    image: docker.io/gitlab/gitlab-ee:16.4.1-ee.0
    hostname: "gitlab.lab.local"
    container_name: "gitlab.lab.local"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.lab.local:18000'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_license_file'] = '/run/secrets/gitlab_license'
        gitlab_rails['initial_root_password'] = 'Vandelay1234'
    ports: 
      - "18000:18000"
      - "18222:2224"
    networks:
      - internal
    secrets:
      - gitlab_license
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_data:/var/opt/gitlab"
    shm_size: "256m"

  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:latest
    container_name: "gitlab-runner"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - gitlab_runner_config:/etc/gitlab-runner
    networks:
      - internal

secrets:
  gitlab_license:
    environment: 

networks:
  internal: {}

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
  gitlab_runner_config: {}
